[platformio]
src_dir = example/src

[env:esp32c3]
platform = espressif32
framework = espidf
board = esp32-c3-devkitc-02
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, direct
lib_deps =
  symlink://.
build_unflags =
  -std=c++11
  -std=gnu++11
  -std=gnu++14
  -std=gnu++17
build_flags =
  -std=gnu++2a
  -Wnarrowing
  -Wno-deprecated
  -Wwrite-strings
  -Wreturn-type
